### PR TITLE
Pki

### PR DESCRIPTION
**Pull request by geofffranks**
Added commands to facilitate working with Vault's PKI backend.

Implements #37

### CODE REVIEW

**Comment by jhunt** [comment]
Revoking a certificate doesn't modify the cert/key/serial stored in the Vault? (not even to annotate that it has been revoked?)

**Comment by geofffranks** [comment]
Thought about that, but if you specify just by serial number, rather than path to vault secret, you don't know where to go to clean up/invalidate. I can make it do that if you specify a secret path, and do nothing if you just specify a serial, or remove serial support outright.

**Comment by jhunt** [comment]
Is it possible to store the real path at `/pki/serial/<serial>` as a symlink of sorts?

**Comment by geofffranks** [comment]
I don't think so, I think we'd have to store it in the secret backend /secret/serials/serial -> path (if it exists).

I'm leaning towards not supporting revoking by serial, since you can use vault cli for that, and the serials aren't something people will likely know off-hand.

**Comment by jhunt** [comment]
Ha.  I meant `secret/pki/serial/<blah>`, but yeah, that takes namespace away from the user.

What's an example of the path you would need for revocation?

I can actually see revoke-by-serial as a thing, since it's the only identifying part of the certificate (unless path-in-vault encodes some identifying info)

**Comment by geofffranks** [comment]
For path, it would be `secret/path/to/certs/common.name.of.cert.com`. Revoke by serial is how Vault's API works, so `safe vault write <convoluted stuff>` will work still. Without having retrieved the serial previosuly (or finding it stored in `secret/path/to/certs/common.name.of.cert.com`), the only way to otherwise get the serial of a certificate to be revoked is query Vault to list all certs, then iterate over each serial, to retrieve the cert, and see if the cert returned matches the one you want. If people are storing serials out-of-band to vault, they  might want the delete-by-cert feature, but that would imply they aren't using safe to begin with, since safe stores the serial automatically.

**Comment by jhunt** [comment]
:+1:

**Pull request merged**
