### PR TITLE
more runes when generating a password

### PR DESCRIPTION
**Pull request by fearoffish**
even though we have a 64 character password, more runes would satisfy my security itch more

### CODE REVIEW

**Comment by jhunt** [comment]
Lots of systems don't allow some of these characters, and since we have no way of specifying _which_ runes to use, I'd rather play it safe.

As for "security", I'll refer you to https://xkcd.com/936/

**Comment by fearoffish** [comment]
I don't decide what clients want for their security. I'll continue with this and see if I can add an option to choose a password policy.

**Comment by geofffranks** [comment]
Maybe a list of allowed characters to add in addition to the default can be specified in saferc?

**Comment by fearoffish** [comment]
Maybe I'm confusing the place I should be changing this though. This might be a genesis change, for those automatically generated passwords.

**Comment by fearoffish** [comment]
Nope, digging through this source more I see it's `safe gen`. A saferc option might be a good idea. I'll look into that. Thanks.

**Comment by jhunt** [comment]
Wait, you said "for security", which is different from "to appease security policy".

I would prefer not to put anything so call-specific in `.saferc`; rather, I'd prefer to see `safe gen <n> <charclass>`, where `<charclass> is one of:

- alpha
- alphanumeric
- numeric
- all
- /<regex>/

**Comment by fearoffish** [comment]
If we go with pre-determined words, then we're going to end up having to edit this for every client that requires something specific.

I was thinking just adding this to the saferc:

```
password_runes: "XYZ"
```

This would allow a client to do whatever they want.

**Comment by fearoffish** [comment]
If we go with pre-determined words, then we're going to end up having to edit this for every client that requires something specific.

I was thinking just adding this to the saferc:

```

password_runes: "XYZ"

```

This would allow a client to do whatever they want.

On Mon, 29 Aug 2016 at 14:46 James Hunt

<
mailto:James Hunt <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

Wait, you said "for security", which is different from "to appease security policy".

I would prefer not to put anything so call-specific in

.saferc

; rather, I'd prefer to see

safe gen <n> <charclass>

, where ` is one of:

alpha

alphanumeric

numeric

all

//

—

You are receiving this because you modified the open/close state.

Reply to this email directly,
https://github.com/starkandwayne/safe/pull/44#issuecomment-243128146
, or

**Comment by jhunt** [comment]
I disagree with using `.saferc` for this, for what that's worth.

**Comment by jhunt** [comment]
Also, you may have missed the `/regex/` option, thanks to my inability to use markdown.

**Comment by fearoffish** [comment]
Updated to use a cli argument.

**Comment by fearoffish** [comment]
Example:

```
safe gen 64 "1-9" secret/random one
```

**Comment by geofffranks** [comment]
👍

**Comment by jhunt** [comment]
I think we can merge this, but we probably want to use getopt-style flags (`-c 'chars'`), so that we can support #52

**Comment by geofffranks** [comment]
@fearoffish can you Update this to resolve merge conflicts + use getopt-style flags?

**Pull request merged**
